# Generated by Django 4.2.30 on 2026-06-14 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField(help_text='Nitrogen ratio in soil (N)')),
                ('phosphorus', models.FloatField(help_text='Phosphorus ratio in soil (P)')),
                ('potassium', models.FloatField(help_text='Potassium ratio in soil (K)')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('humidity', models.FloatField(help_text='Humidity ratio in %')),
                ('ph', models.FloatField(help_text='Soil pH value')),
                ('rainfall', models.FloatField(help_text='Rainfall amount in mm')),
                ('recommended_crop', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
